---
- name: "Chocolatey"
  hosts: windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
            - chocolatey
            - chocolatey-core.extension
          state: present
    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present
    - name: Install Bootstrap Studio
        win_chocolatey:
        name: bootstrap-studio.install
        state: present
    - name: Install Adobe Reader
      win_chocolatey:
        name: adobereader
        state: present
    - name: Install GitHub Desktop
      win_chocolatey:
        name: github-desktop
        state: present 
    - name: Install Open VPN
      win_chocolatey:
        name: openvpn
        state: present
        state: present
    - name: Install Visual Studio
      win_chocolatey:
        name: visualstudio2019professional
        state: present
    - name: Install 7Zip
      win_chocolatey:
        name: 7zip
        state: present
    - name: Install IIS Server
      win_feature:
        name:
         - Web-Server
         - Web-Mgmt-Console
        state: present
    - name: Install Web Deploy
      win_chocolatey:
        name:choco install webdeploy
        state: present
        


