---
- name: "Chocolatey"
  hosts: CAD
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
            - chocolatey
            - chocolatey-core.extension
          state: present
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes
    - name: Install FireFox
      win_chocolatey:
        name: firefox
        state: present
    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present

        