---
- name: "Chocolatey"
  hosts: windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
            - chocolatey
            - chocolatey-core.extension
          state: present
    - name: Install Dell Command Update
      win_chocolatey:
        name: dellcommandupdate
        state: present
    - name: Install NVIDIA Managment
      win_chocolatey:
        name: geforce-experience
        state: present
    - name: Install NVIDIA Drivers
      win_chocolatey:
        name: geforce-game-ready-driver
        state: present
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes
    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present
    - name: Install Visual Studio
      win_chocolatey:
        name: visualstudio2019professional
        state: present
    - name: Install Adobe Reader
      win_chocolatey:
        name: adobereader
        state: present
    - name: Install GitHub Desktop
      win_chocolatey:
        name: github-desktop
        state: present 
    - name: Install TeamViewer
      win_chocolatey:
        name: teamviewer
        state: present
    - name: Install Draw.io
      win_chocolatey:
        name: drawio
        state: present
    - name: Install Zoom
      win_chocolatey:
        name: zoom
        state: present
    - name: Install VLC Media Player
      win_chocolatey:
        name: vlc
        state: present
    - name: Install Office365
      win_chocolatey:
        name: office365business
        state: present
    - name: Install 7Zip
      win_chocolatey:
        name: 7zip
        state: present
    - name: Install Cmder
      win_chocolatey:
        name: cmder
        state: present
    - name: Install WinSCP
      win_chocolatey:
        name: winscp
        state: present
    - name: Install Docker Desktop
      win_chocolatey:
        name: docker-desktop
        state: present
    - name: Install VS Code Docker Extension
      win_chocolatey:
        name: vscode-docker
        state: present
    - name: Install kubectl
      win_chocolatey:
        name: kubernetes-cli
        state: present
    - name: Install MiniKube
      win_chocolatey:
        name: minikube
        state: present